name: React Static CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, macOS, react-2-do]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build
        env:
          CI: false

      - name: Package build (Contents only)
        # We 'cd' into build so the zip doesn't contain a top-level 'build/' folder
        run: |
          cd build && zip -r ../react-build-${{ github.sha }}.zip .

      - name: Upload to Nexus
        run: |
          curl -v -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} \
          --upload-file react-build-${{ github.sha }}.zip \
          ${{ secrets.NEXUS_URL }}/react-build-${{ github.sha }}.zip

      - name: Upload build artifact (GitHub backup)
        uses: actions/upload-artifact@v4
        with:
          name: react-build-${{ github.sha }}
          path: build

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download artifact from Nexus
        run: |
          curl -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} \
          -o react-build.zip \
          ${{ secrets.NEXUS_URL }}/react-build-${{ github.sha }}.zip

    #   - name: Clean and Deploy
    #     run: |
    #       # 1. Create directory if missing
    #       sudo mkdir -p /var/www/react-app
          
    #       # 2. Clear old files
    #       sudo rm -rf /var/www/react-app/*
          
    #       # 3. Extract new files directly into target
    #       sudo unzip react-build.zip -d /var/www/react-app/
          
    #       # 4. Fix permissions for Nginx
    #       sudo chown -R www-data:www-data /var/www/react-app
          
    #       # 5. Reload Nginx
    #       sudo systemctl reload nginx